services:
    tiketin-v2-be:
        image: dta32/tiketin-v2-be
        container_name: tiketin-v2-be
        env_file: .env
        ports:
            - "7004:80"
        networks:
            - tiketin-net

    tiketin-v2-db:
        image: mysql:8.0.39
        container_name: tiketin-v2-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tiketin
            MYSQL_USER: tiketin
            MYSQL_PASSWORD: tiketin
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - tiketin-net

    tiketin-v2-fe:
        image: dta32/tiketin-v2-fe
        container_name: tiketin-v2-fe
        ports:
            - "7003:80"

networks:
    tiketin-net:
        driver: bridge

volumes:
    dbdata:
        driver: local
