version: "3"

services:
    web:
        environment:
            - APACHE_RUN_USER=#1000
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:80
        extra_hosts:
            - "host.docker.internal:host-gateway"
