services:
    tiketin-be-core:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tiketin-be-core
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - tiketin-net

    tiketin-be-db:
        image: mysql:8.0.39
        container_name: tiketin-be-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tiketin
            MYSQL_USER: tiketin
            MYSQL_PASSWORD: tiketin
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - tiketin-net

    tiketin-be-webserver:
        image: nginx:latest
        container_name: tiketin-be-webserver
        restart: unless-stopped
        ports:
            - "7004:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./:/var/www/html
        networks:
            - tiketin-net

networks:
    tiketin-net:
        driver: bridge

volumes:
    dbdata:
        driver: local
