apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: tiketin-v2-db-pvc
spec:
    resources:
        requests:
            storage: 5Gi
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
